### ISSUE TITLE
Some casuistries not covered on JS

### ISSUE THREAD

**Issue by Proogresa** [slav123/CodeIgniter-minify#10]
## 1

```
data: {
  customer_email: customer_email,
  customer_firstname: customer_firstname,
}
```

Last colon is an error, but jQuery skip that with no issue.
The minifier returns an empty script when it founds that.
## 2

When the minifier detects on the array of files a file modified after the last time, it generates the resulting script, it generates a new one. It rocks. But...
When you add to the array of files a new file wich its last modified date is previous to the resulting script modified date, it does not generates a new one.

**Comment by slav123** [comment]
in latest release just introduced new js compression engines, so problem should be solved. stil not sure how to address second issue, without keeping some kind of metadata around builds
