### ISSUE TITLE
More Directories

### ISSUE THREAD

**Issue by aroon9002ahmed** [slav123/CodeIgniter-minify#27]
Hello
how i can set my another files Directories
for example:
Assets/css/bootstrap/bootstrap.min.css
Assets/css/font-awesome/font-awesome.min.css 

thank you

**Comment by slav123** [comment]
assuming your asset directory is "assets/css" you can add them by using array (['bootstrap/bootstrap.min.css', 'font-awesome/font-awesome.min.css'])
