### ISSUE TITLE
Too many compiles performed recently. Try again

### ISSUE THREAD

**Issue by shubhampatel30** [slav123/CodeIgniter-minify#35]
With closure compiler have a issue related to limit of requesting method in an hours.
you have any solution related to this problem. please share with me.

Thanks

**Comment by slav123** [comment]
You have 2 option there.. one is to "generate" minified files, and then setup

 `echo $this->minify->deploy_js(FALSE); ` 

so it doesn't push file to recompile, second option is to use another compressor for JS minification

 `// compression engine setting (default values: 'minify' and 'closurecompiler')
$config['compression_engine'] = array(
	'css' => 'minify', // minify || cssmin
	'js'  => 'closurecompiler' // closurecompiler || jsmin || jsminplus
);
`

**Comment by shubhampatel30** [comment]
thanks you so much.
