### ISSUE TITLE
how can i make a group of two compressed js for four different js files?

### ISSUE THREAD

**Issue by sumitkalia** [slav123/CodeIgniter-minify#38]
In total, i have 4 js files and i would like to make 2 different groups of 2 js each with compression. The current deploy_js adds the rest of two in previous compressed two.

	 $this->minify->add_js('pace.min.js')->add_js('animsition.min.js');
	 echo $this->minify->deploy_js();
	 $this->minify->add_js('scrollreveal.min.js')->add_js('footer.js');
	 echo $this->minify->deploy_js();

Any thought?

**Comment by michalsn** [comment]
Yes, it's possible with all methods: css(), js(), add_css() and add_js(). We have second parameter for this.
```
$this->minify->add_js(['pace.min.js', 'animsition.min.js']);
$this->minify->add_js(['scrollreveal.min.js', 'footer.js'], 'extra');
echo $this->minify->deploy_js();
```

**Comment by sumitkalia** [comment]
Thanks Michalsn. It worked. I forgot to see the updates in thread.
