### ISSUE TITLE
Increase in server response time

### ISSUE THREAD

**Issue by sumitkalia** [slav123/CodeIgniter-minify#41]
I have used a couple of js and css under compression on local server and tested it at Google Page Speed tool. 

Now there is a server response delay of 4 sec. Any chance, I can reduce it to the min?

My code:
$this->minify->add_js(['1.js','2.js','3.js','4.js','5.js','6.js','7.js'], 'essentials_javascript'); 
$this->minify->deploy_js();

**Comment by slav123** [comment]
change compression engine to **jsmin** so files won't be send to closurecompiler api. once they cached - scrip only checks timestamps.
```
// compression engine setting (default values: 'minify' and 'closurecompiler')
$config['compression_engine'] = array(
	'css' => 'cssmin', // minify || cssmin
	'js'  => 'jsmin' // closurecompiler || jsmin || jsminplus
);
```
