### ISSUE TITLE
I wonder if that's possible!

### ISSUE THREAD

**Issue by sumitkalia** [slav123/CodeIgniter-minify#43]
"compression_engine" works like a charm! Can we obfuscate div ids or classes name as well and put it back to  html page. For e.g.
--------------------Input--------------------------
<body>
<div class="test" id="hi">This is an idea</div>
</body>

..... css file .... 
#hi{ 
color:black;
}
.test{
font-size:1rem;
}

-------------------Output--------------------------
<body><div class="0typs_123" id="lpsd">This is an idea</div></body>

..... css file .... 
#0typs_123{ color:black;}.lpsd{font-size:1rem;}

**Comment by slav123** [comment]
don't see the point. a lot computer power to handle something like that, and value is not worth of it.
