### ISSUE TITLE
Add clearstatcache();

### ISSUE THREAD

**Issue by dejurin** [slav123/CodeIgniter-minify#45]
When I develop an application, I often reload the script data, but the "filesize" function in "linux" has a cache. Subsequently, files are not generated until the end.

Add before
```
clearstatcache();
$contents = fread($handle, filesize($out_file));
```

**Comment by michalsn** [comment]
Nice catch. We will switch to `file_get_contents` since it's a recommended way to handle loading file source to variable.

Thanks.

**Comment by dejurin** [comment]
Thank U
