### ISSUE TITLE
Closurecompiler and jsminplus don't work

### ISSUE THREAD

**Issue by dankolosov** [slav123/CodeIgniter-minify#57]
Hi.
Have a problem with config
$config['compression_engine']['js'] = 'closurecompiler';

The compiled file is empty.
'jsminplus' doesn't work too.

Thanks

**Comment by michalsn** [comment]
I couldn't reproduce the problem.

1. What is your Codeigniter and PHP version?
2. Can you provide any js files?
3. Is it happening always - even with small and simple files?

**Comment by michalsn** [comment]
See #58
