### ISSUE TITLE
Change base_url to static_url

### ISSUE THREAD

**Issue by tenq** [slav123/CodeIgniter-minify#63]
Hi, it`s possible to use my **static_url** instead a **base_url**?

**Comment by michalsn** [comment]
Good idea, this can be useful.

Now it's possible - just download the latest code from the repo.

You can set this with `$config['base_url']` variable in `application/config/minify.php` file or by a direct call in your code:  `$this->minify->base_url = 'https://my.super.duper.domain/'`
