### ISSUE TITLE
$config['js_file'] not working properly

### ISSUE THREAD

**Issue by manukieli** [slav123/CodeIgniter-minify#65]
I'm using this code
`        $this->load->library('minify');
        $minify_config['js_file'] = 'newtable.js';
        $minify = new Minify($minify_config);
        $minify->js(array('tables.js'));`

I want my own name of js_file, but they return me alway the same js name file: script.min.js
I'm using PHP7.2

**Comment by michalsn** [comment]
Yep... nice catch - thanks :)

One thing - you can simplify your code by doing this:

```php
$minify_config['js_file'] = 'newtable.js';
$this->load->library('minify', $minify_config);
$this->minify->js(array('tables.js'));
```
