### ISSUE TITLE
Need to look in more than one file

### ISSUE THREAD

**Issue by pradeeshattlee** [slav123/CodeIgniter-minify#68]
hi 
Is it possible to look for js or css files in more than one location how to specify in minify.php config
(where to look for js files (default value: 'assets/js'))

**Comment by michalsn** [comment]
Hi,

No, it's not possible right now. But quality pull-request may change it :) 

To be honest, I don't really see the point of implementing such a thing. If you want to group your assets you can always use subfolders. The idea of checking many different folders for finding files every time doesn't speak to me at all.
