### ISSUE TITLE
Browser cache does not work with the library

### ISSUE THREAD

**Issue by Guri-ksolves** [slav123/CodeIgniter-minify#69]
Hi all,
I tried to use the library and I was able to generate minified files for CSS and JS, but then I realized that the browser is not caching them and every time it was fetching these files from the server.
Is there any way we can use the browser cache functionality along with this library. 
Thanks.

**Comment by michalsn** [comment]
Hi,
There is nothing that stops you from embracing browser cache with this library. Just make sure you're serving static files with proper headers on your server.
