### ISSUE TITLE
Difficult to run every time

### ISSUE THREAD

**Issue by sina3security** [slav123/CodeIgniter-minify#79]
Hi
My problem is that in my project, every time the page loads, the library runs and re-compresses the files.
This will cause heavy loading.
How to set it to run once every 3 days, for example.
Or just run again in case of changes?

**Comment by slav123** [comment]
You can set this up using correct prams. `echo $this->minify->deploy_css(TRUE);`  will skip rebuilding CSS files, `echo $this->minify->deploy_css();` will check if files were modified and then rebuild

**Comment by sina3security** [comment]
> You can set this up using correct prams. `echo $this->minify->deploy_css(TRUE);` will skip rebuilding CSS files, `echo $this->minify->deploy_css();` will check if files were modified and then rebuild

thank you
