### ISSUE TITLE
Should only throw error on deploy

### ISSUE THREAD

**Issue by Goddard** [slav123/CodeIgniter-minify#80]
I noticed in this library it throws an error early on even if the library doesn't need write access.

For example 
`get_instance()->load->library('minify');`

It throws an error here or rather in the constructor which runs `_config_checks()`.

It should only do the config checks if called on, or when about to actually do writing. 

My situation it doesn't make sense to regenerate the file in production.  It only makes sense to regenerate my css and js files in development and when I deploy completely shut off the generation because it just costs extra seconds that it doesn't need to waste.

I can make a pull request if you like, or am I missing something?

Thanks

**Comment by sina3security** [comment]
It is true.
This is exactly my problem.

**Comment by slav123** [comment]
Let me know if it solves your problem

**Comment by Goddard** [comment]
Looks good.
